### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by zoenglinghou** [znerol/prometheus-pve-exporter#109]
Hello,

I am trying to setup `grafana` with `prmetheus-pve-exporter`. After the setup, I am not able to get any data, and the `systemd` log returns:

```
Mar 28 13:15:46 fedora pve_exporter[61761]: Exception thrown while rendering view
Mar 28 13:15:46 fedora pve_exporter[61761]: Traceback (most recent call last):
Mar 28 13:15:46 fedora pve_exporter[61761]:   File "/usr/local/lib/python3.10/site-packages/pve_exporter/http.py", line 96, in view
Mar 28 13:15:46 fedora pve_exporter[61761]:     return view_registry[endpoint](**params)
Mar 28 13:15:46 fedora pve_exporter[61761]:   File "/usr/local/lib/python3.10/site-packages/pve_exporter/http.py", line 38, in on_pve
Mar 28 13:15:46 fedora pve_exporter[61761]:     output = collect_pve(self._config[module], target, self._collectors)
Mar 28 13:15:46 fedora pve_exporter[61761]:   File "/usr/local/lib/python3.10/site-packages/pve_exporter/collector.py", line 332, in collect_pve
Mar 28 13:15:46 fedora pve_exporter[61761]:     return generate_latest(registry)
Mar 28 13:15:46 fedora pve_exporter[61761]:   File "/usr/local/lib/python3.10/site-packages/prometheus_client/exposition.py", line 171, in generate_latest
Mar 28 13:15:46 fedora pve_exporter[61761]:     for metric in registry.collect():
Mar 28 13:15:46 fedora pve_exporter[61761]:   File "/usr/local/lib/python3.10/site-packages/prometheus_client/registry.py", line 83, in collect
Mar 28 13:15:46 fedora pve_exporter[61761]:     yield from collector.collect()
Mar 28 13:15:46 fedora pve_exporter[61761]:   File "/usr/local/lib/python3.10/site-packages/pve_exporter/collector.py", line 45, in collect
Mar 28 13:15:46 fedora pve_exporter[61761]:     for entry in self._pve.cluster.status.get():
Mar 28 13:15:46 fedora pve_exporter[61761]:   File "/usr/local/lib/python3.10/site-packages/proxmoxer/core.py", line 143, in get
Mar 28 13:15:46 fedora pve_exporter[61761]:     return self(args)._request("GET", params=params)
Mar 28 13:15:46 fedora pve_exporter[61761]:   File "/usr/local/lib/python3.10/site-packages/proxmoxer/core.py", line 129, in _request
Mar 28 13:15:46 fedora pve_exporter[61761]:     errors=(self._store["serializer"].loads_errors(resp) or {}),
Mar 28 13:15:46 fedora pve_exporter[61761]:   File "/usr/local/lib/python3.10/site-packages/proxmoxer/backends/https.py", line 180, in loads_errors
Mar 28 13:15:46 fedora pve_exporter[61761]:     return json.loads(response.text)["errors"]
Mar 28 13:15:46 fedora pve_exporter[61761]: KeyError: 'errors'
Mar 28 13:15:46 fedora pve_exporter[61761]: 127.0.0.1 - - [28/Mar/2022 13:15:46] "GET /pve?module=default&target=<Proxmox IP>HTTP/1.1" 500 -
```

I searched the tickets but couldn't find anything. Is it something that I setup incorrectly?

Love the project, and thanks in advanced for you help!

**Comment by zoenglinghou** [comment]
Also my configs:
Prometheus:
```yaml
global:
  scrape_interval: 15s
  external_labels:
    monitor: codelab-monitor
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: pve
  static_configs:
  - targets:
    - <Proxmox IP>
  metrics_path: /pve
  params:
    module: [default]
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: 127.0.0.1:9221
```

and pve-exporter:
```yaml
default:
  user: prometheus@pve
  token_name: prometheus_pve
  token_value: <TOKEN VALUE>
  verify_ssl: false
```

This is what I see in grafana:
![image](https://user-images.githubusercontent.com/11689106/160808473-ed876b2e-4c86-45c8-8331-3144c99304bc.png)

**Comment by zoenglinghou** [comment]
Ok I solved the issue per this post: https://forum.proxmox.com/threads/empty-api-response-when-getting-vms.80330/

> I found the problem. I needed to add a permission for the token AND the user the token was tied to. Everything's working now.

I had the token set to the right permission, but not the user itself.
